### ISSUE TITLE
Reducing crushing delay

### ISSUE THREAD

**Issue by mstempell** [wsdfhjxc/crush-those-cookies#17]
Could the crushing delay be reduced under 10 seconds?
Any reason for this minimal delay?

**Comment by wsdfhjxc** [comment]
You can change the delay to be anything between 0 and 600 seconds in preferences.

However, since I'm not using Pale Moon for a long time, this extension is not maintained anymore. Instead, I suggest trying out a better alternative, that is Cookies Exterminator by JustOff.

**Comment by mstempell** [comment]
Thanks for the fast reply.
I am actually using Cookies Exterminator, which i thought was just a "compatibility fork".
I will post my issue there then (because even though you can enter a lower delay, it resets to 10 when closing the options window by clicking 'Accept').

**Comment by wsdfhjxc** [comment]
Yeah, there are some major differences between these two extensions.
