### ISSUE TITLE
Too strict by default

### ISSUE THREAD

**Issue by wsdfhjxc** [wsdfhjxc/crush-those-cookies#3]
Currently all cookies coming from domains other than those directly bound with opened documents (or those which are whitelisted) are being removed. Many services use subdomains for stored cookie data in order to get the the whole thing working but they present their content on different domains. For example, accessing a Gmail account is impossible without whitelisting _.google.com_ because of this.

By default the extension should not only compare cookies' domain names with opened documents' domain names for exact equality but also take subdomains relationship into account. It should be also possible to disable this in the extension's preferences.

**Comment by grumpygeek** [comment]
I like it how it is working now - blast everything not on white list.  (I do have 3rd party set to never in the browser; nothing currently whitelisted.)  

I often open threads I want to read in separate tabs from the index.   And on PM forum, when I close one of those tabs, CTC crushes a cookie.  Seems to happen every time.  Not a problem for me or the PM forum; just wanted to mention it.  I think the ones being deleted are for just palemoon.com, whereas the one(s) remaining for the index are for forum.palemoon.com.

**Comment by wsdfhjxc** [comment]
Yes, while browsing PM forum beside _forum.palemoon.org_ domain there are also created cookies registered for _palemoon.org_ domain and they had been removed because of this issue. Now it's going to be less strict by default and it won't remove cookies from subdomains when parent domain is opened and vice versa. There is also a new toggle in preferences (Enable strict domain and subdomain checking) which can bring back the strict behavior after checking it.
