### ISSUE TITLE
Button positioning still not handled properly

### ISSUE THREAD

**Issue by wsdfhjxc** [wsdfhjxc/crush-those-cookies#5]
Currently the button can be placed either in nav-bar or addon-bar. Placing it elsewhere (e.g. TabsToolbar) isn't handled properly and the button's position is being dropped at the browser restart.

**Comment by grumpygeek** [comment]
In the version you made in response to my missing icon issue, it placed the icon on left side of addon bar (bottom left corner).   I almost thought it was completely missing before I noticed it there.  But, it has been completely stable so for me that position is a good trade off.  I have not tried moving since then.  That position was retained when I installed 1.0 release without uninstalling.

**Comment by LimboSlam** [comment]
@grumpygeek: Thats great for you, but this issue wasn't present for me in v0.4.0 untilI updated to v1.0 of CTC. I also like my UI a bit neater as I need all the possible room available for me on some of my older, smaller screens. Yeah I have 3 add-ons in TabsToolbar and then everything else runs in the background or placed inside context menu for functionality.  

So I hope this small issue can get fixed, if not thats alright. I'll just have to adapt or stick with SDC until @wsdfhjxc gets workable fix out. But I know @wsdfhjxc is the guy for the job and will definitely work out the bugs. 

Thanks man! :+1:

**Comment by wsdfhjxc** [comment]
It should be now possible to place the button anywhere in the customizable UI parts and keep that position.

**Comment by grumpygeek** [comment]
I was just addressing the default placement, not every possible position.  If he chooses to support allowing it to be placed on the tabs toolbar that is his choice.  I think that it is really petty to say it has be there; I would label that RESOLVED: WONTFIX.  We're lucky to even have an SDC alternative.

**Comment by LimboSlam** [comment]
@grumpygeek: I think you got the wrong impression of me, sorry about that. 

@wsdfhjxc: I'm sorry if I came out to demanding, I really am. Yeah! Now thanks for all your hard work! :+1:

**Comment by wsdfhjxc** [comment]
No, it's fine. It was my silliness to support only nav-bar and addon-bar while Pale Moon is heavily customizable when it comes to the UI. I hope it works correctly now, but let me know if something's wrong. Thank you guys for your involvement.

**Comment by LimboSlam** [comment]
@wsdfhjxc! Yes the button now stays positioned when I restart Pale Moon. 

Although I just got word from a friend (who I recommended this add-on to) that when changing themes and going back to the default theme, CTC now re-positioned itself to the left side of the Australium theme on the nav-bar. 

Now I can't confirm this as I'm out on a business trip and will be back tomorrow (forgot my personal laptop and all USB's restricted; no Pale Moon for the day!), so maybe you could check this out as I too use the same theme, full theme from APO. 

Thanks!

**Comment by wsdfhjxc** [comment]
@LimboSlam, That's strange. I can't reproduce this issue. Switching between various themes back and forth makes no difference. The icon stays in the same place every time after a restart.
