### ISSUE TITLE
What is strict checking?

### ISSUE THREAD

**Issue by sergeevabc** [wsdfhjxc/crush-those-cookies#6]
Dear @wsdfhjxc, could you be so kind to tell what “strict sub/domain checking” does? My initial guess is that its unchecked state allows white-listing domains without adding asterisk or dot in the beginning yet having both domain with sub-domains parsed, for example, “asana.com” would work as “.asana.com”.

**Comment by wsdfhjxc** [comment]
When it's disabled, the extension doesn't remove cookies from a specific domain when a website with a sub/parent domain for that one is open. For example, when _forum.palemoon.org_ is being closed and its parent _palemoon.org_ remains open, then cookies from _forum.palemoon.org_ aren't removed.

When it's enabled, the extension strictly compares domains with these in open websites and removes cookies from domains which didn't get any match. For example, when _forum.palemoon.org_ is being closed and its parent _palemoon.org_ remains open, then cookies from _forum.palemoon.org_ are plainly removed (or not if whitelisted, but that's a separate check).

I realize some preferences may be confusing and their naming doesn't help that. I'll provide more detailed descriptions some day if this extension will be getting some interest.

**Comment by sergeevabc** [comment]
Thank you, @wsdfhjxc.

**Comment by sergeevabc** [comment]
This issue should be labeled as question, right?
