### ISSUE TITLE
Settings aren't saved when restarting the browser

### ISSUE THREAD

**Issue by roranicus** [wsdfhjxc/crush-those-cookies#7]
Title is self-explanatory. I changed some of the settings, mainly reduced the delay to 1 seconds, disabled logging, and disabled the notification. When restarting the browser, the settings reset to default. 

Using Palemoon 26.5.0 on Linux Mint 17.3. I can include a list of other addons I use that might conflict if necessary. I pretty much have all forms of history disabled, my setup is very privacy-centered.

**Comment by wsdfhjxc** [comment]
That's strange. Are you sure you pressed Apply changes button in preferences window before closing it? If you manually change some preferences in about:config (eg. extensions.crush-those-cookies.enableNotifications) and restart the browser does the problem still persist?

**Comment by roranicus** [comment]
Pressing Apply doesn't work, but changing the settings manually in the config menu works. 

Another issue I noticed is that when I shut down the browser, I get the following error message: "This window might be busy and is not responding. Do you want to terminate the application?" This only happens if the addon is activated. I might or might not be related, I can open a second issue if you want.

**Comment by wsdfhjxc** [comment]
So, there is another problem with running this extension in PM for Linux. I'm not sure how can this be platform dependent but I'll take a look at this whole thing. Thanks for reporting.

**Comment by wsdfhjxc** [comment]
Because of the way preferences saving is handled by this extension, this issue was a thing on Linux due to the previous browser exit problem.
